# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190625_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='total_polled',
            field=models.CharField(max_length=200),
        ),
    ]
