# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190625_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='total_polled',
            field=models.IntegerField(default=0),
        ),
    ]
